version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "SM hello world" > ~/output.txt;
              pwd;
              ls;
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
         at: ~/
      - run: cat ~/output1.txt
      
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 0
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail
      - run:
          name: on pass
          command: echo "PASS"
          when: on_success

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - my_job

      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
